# Generated by Django 4.1.4 on 2022-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True)),
                ("Tweet_Text", models.CharField(max_length=500)),
                ("Trend_score", models.FloatField()),
                ("IMAGE_URL", models.URLField(blank=True)),
                ("video_img_url", models.URLField(blank=True)),
                ("item_id", models.IntegerField()),
                ("Brand", models.CharField(max_length=500)),
                ("Sub_Category", models.CharField(max_length=500)),
                ("Flipkart_url", models.URLField(blank=True)),
                ("product_image_link", models.URLField(blank=True)),
                ("product_title", models.CharField(max_length=500)),
            ],
        ),
    ]
