# Generated by Django 4.1.4 on 2023-02-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HashtagList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.IntegerField()),
                ("hash_tag", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True)),
                ("Tweet_Text", models.CharField(max_length=500)),
                ("Trend_score", models.FloatField()),
                ("IMAGE_URL", models.URLField(blank=True, max_length=5000)),
                ("video_img_url", models.URLField(blank=True, max_length=5000)),
                ("item_id", models.IntegerField()),
                ("Brand", models.CharField(max_length=500)),
                ("Sub_Category", models.CharField(max_length=500)),
                ("Flipkart_url", models.URLField(blank=True, max_length=5000)),
                ("product_image_link", models.URLField(blank=True)),
                ("product_title", models.CharField(max_length=500)),
                (
                    "hashtaglist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.hashtaglist",
                    ),
                ),
            ],
        ),
    ]
