# Generated by Django 4.1.4 on 2022-12-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="Flipkart_url",
            field=models.URLField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="card",
            name="IMAGE_URL",
            field=models.URLField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="card",
            name="video_img_url",
            field=models.URLField(blank=True, max_length=5000),
        ),
    ]
