# Generated by Django 4.1.4 on 2023-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_card_hashtaglist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploadfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
